# Generated by Django 4.1.7 on 2023-02-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="advert_type",
            field=models.CharField(
                choices=[
                    ("Cpp", "cpp"),
                    ("History", "History"),
                    ("Cyber Security", "Cyber Security"),
                ],
                max_length=50,
                verbose_name="Subject",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="course_time",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=8,
                verbose_name="Course Time(hours)",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="lectures",
            field=models.DecimalField(
                decimal_places=2, default=1.0, max_digits=8, verbose_name="Lectures"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("Traditional", "Traditional"),
                    ("Electronic", "Electronic"),
                    ("Official", "Official"),
                    ("Additional", "Additional"),
                    ("Commercial", "Commercial"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=50,
                verbose_name="Type course",
            ),
        ),
    ]
